In [1]:
from sklearn.datasets import make_classification
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\suraj\Desktop\Brunel MPhil\Closing Price Research\Index Master Sheet Updated.csv")

In [3]:
data

,Date,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
0,30-12-2022,3839.50,511646752.0,724693120.0,26094.50,19781.41,3871.63,7038.688,NaN,18105.3,...,3251.32,3793.62,7451.74,6473.76,13923.59,23706.96,689.01,2043.404,10729.40,970.60
1,29-12-2022,3849.28,466689120.0,729421504.0,26093.67,19741.14,3856.70,7020.063,2236.40,18191.0,...,3249.24,3850.07,7512.72,6573.47,14071.72,24056.55,701.01,2075.313,10857.35,936.80
2,28-12-2022,3783.22,438066304.0,740323072.0,26340.50,19898.91,3871.26,7086.407,2280.45,18122.5,...,3266.97,3808.82,7497.19,6510.49,13925.60,23770.44,694.84,2052.762,10812.67,933.76
3,27-12-2022,3829.25,449987360.0,754168384.0,26447.87,NaN,3887.85,NaN,2332.79,18132.3,...,3266.38,3832.89,NaN,6550.66,13995.10,23855.86,701.06,2067.607,10839.22,960.51
4,23-12-2022,3844.82,407580896.0,763465024.0,26235.25,19593.06,3828.22,7107.689,2313.69,17806.8,...,3257.70,3817.01,7473.01,6504.90,13940.93,23877.55,701.06,2054.329,10804.68,963.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.dtypes

Date                       object
Last Price                float64
Volume                    float64
SMAVG (15)                float64
NIKKEI 225                float64
HANG SENG                 float64
SHANGHAI                  float64
SP ASX 200                float64
KOSPI  100                float64
NIFTY 50                  float64
TAIWAN INDEX              float64
JAKARTA COMPOSITE         float64
FTSE BURSA MAL TOP 100    float64
STRAITS TIMES             float64
EURO STOXX 50 PR          float64
FTSE 100 INDEX            float64
CAC 40 INDEX              float64
DAX INDEX                 float64
FTSE MIB INDEX            float64
AEX INDEX                 float64
OMX STOCKHOLM INDEX       float64
SWISS MARKET INDEX        float64
RTS INDEX                 float64
dtype: object

In [5]:
data['Date'] = pd.to_datetime(data['Date'],format='%d-%m-%Y')
data

,Date,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
0,2022-12-30,3839.50,511646752.0,724693120.0,26094.50,19781.41,3871.63,7038.688,NaN,18105.3,...,3251.32,3793.62,7451.74,6473.76,13923.59,23706.96,689.01,2043.404,10729.40,970.60
1,2022-12-29,3849.28,466689120.0,729421504.0,26093.67,19741.14,3856.70,7020.063,2236.40,18191.0,...,3249.24,3850.07,7512.72,6573.47,14071.72,24056.55,701.01,2075.313,10857.35,936.80
2,2022-12-28,3783.22,438066304.0,740323072.0,26340.50,19898.91,3871.26,7086.407,2280.45,18122.5,...,3266.97,3808.82,7497.19,6510.49,13925.60,23770.44,694.84,2052.762,10812.67,933.76
3,2022-12-27,3829.25,449987360.0,754168384.0,26447.87,NaN,3887.85,NaN,2332.79,18132.3,...,3266.38,3832.89,NaN,6550.66,13995.10,23855.86,701.06,2067.607,10839.22,960.51
4,2022-12-23,3844.82,407580896.0,763465024.0,26235.25,19593.06,3828.22,7107.689,2313.69,17806.8,...,3257.70,3817.01,7473.01,6504.90,13940.93,23877.55,701.06,2054.329,10804.68,963.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1595,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1596,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1597,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1598,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data.dtypes

Date                      datetime64[ns]
Last Price                       float64
Volume                           float64
SMAVG (15)                       float64
NIKKEI 225                       float64
HANG SENG                        float64
SHANGHAI                         float64
SP ASX 200                       float64
KOSPI  100                       float64
NIFTY 50                         float64
TAIWAN INDEX                     float64
JAKARTA COMPOSITE                float64
FTSE BURSA MAL TOP 100           float64
STRAITS TIMES                    float64
EURO STOXX 50 PR                 float64
FTSE 100 INDEX                   float64
CAC 40 INDEX                     float64
DAX INDEX                        float64
FTSE MIB INDEX                   float64
AEX INDEX                        float64
OMX STOCKHOLM INDEX              float64
SWISS MARKET INDEX               float64
RTS INDEX                        float64
dtype: object

In [7]:
#Print the shape of Dataframe  and Check for Null Values
print("Dataframe Shape:", data.shape)
print("Null Value Present:", data.isnull().values.any())

Dataframe Shape: (1599, 23)
Null Value Present: True

In [8]:
data.isna()

,Date,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
0,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,True,False,False,...,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1595,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1596,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1597,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1598,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [9]:
data.isna().sum()

Date                       89
Last Price                 89
Volume                     89
SMAVG (15)                 89
NIKKEI 225                183
HANG SENG                 157
SHANGHAI                  187
SP ASX 200                120
KOSPI  100                171
NIFTY 50                  158
TAIWAN INDEX              180
JAKARTA COMPOSITE         180
FTSE BURSA MAL TOP 100    173
STRAITS TIMES             131
EURO STOXX 50 PR           98
FTSE 100 INDEX            106
CAC 40 INDEX              102
DAX INDEX                 118
FTSE MIB INDEX            113
AEX INDEX                 102
OMX STOCKHOLM INDEX       128
SWISS MARKET INDEX        128
RTS INDEX                 155
dtype: int64

In [10]:
data.sort_values(by='Last Price')

,Date,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
700,2020-03-23,2237.40,1.128845e+09,1.222663e+09,16887.78,21696.13,3530.31,4546.035,1482.46,7610.25,...,2233.48,2485.54,4993.89,3914.31,8741.15,15559.80,423.72,1292.274,8160.79,883.78
1509,2017-01-03,2257.83,6.492194e+08,5.699957e+08,NaN,22150.40,3342.23,5733.183,2043.97,8192.25,...,2898.97,3315.02,7177.89,4899.33,11584.24,19573.48,487.99,1534.697,8316.18,1189.32
1498,2017-01-19,2263.69,5.117236e+08,5.216522e+08,19072.25,23049.96,3329.29,5692.184,2072.79,8435.10,...,3008.22,3290.33,7208.44,4841.14,11596.89,19490.96,484.64,1513.917,8273.08,1136.62
1496,2017-01-23,2265.20,5.348404e+08,5.569024e+08,18891.03,22898.52,3364.08,5610.972,2065.99,8391.50,...,3025.48,3273.04,7151.18,4821.41,11545.75,19328.41,482.71,1504.688,8229.01,1137.67
1500,2017-01-17,2267.89,6.074138e+08,4.938320e+08,18813.53,22840.97,3326.36,5699.420,2071.87,8398.00,...,3012.77,3285.04,7220.38,4859.69,11540.00,19296.16,481.77,1507.320,8304.10,1156.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1595,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1596,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1597,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1598,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    1510 non-null   datetime64[ns]
 1   Last Price              1510 non-null   float64
 2   Volume                  1510 non-null   float64
 3   SMAVG (15)              1510 non-null   float64
 4   NIKKEI 225              1416 non-null   float64
 5   HANG SENG               1442 non-null   float64
 6   SHANGHAI                1412 non-null   float64
 7   SP ASX 200              1479 non-null   float64
 8   KOSPI  100              1428 non-null   float64
 9   NIFTY 50                1441 non-null   float64
 10  TAIWAN INDEX            1419 non-null   float64
 11  JAKARTA COMPOSITE       1419 non-null   float64
 12  FTSE BURSA MAL TOP 100  1426 non-null   float64
 13  STRAITS TIMES           1468 non-null   float64
 14  EURO STOXX 50 PR        1501 non-null   float64
 15  FTSE 100 INDEX          1493 non-null   float64
 16  CAC 40 INDEX            1497 non-null   float64
 17  DAX INDEX               1481 non-null   float64
 18  FTSE MIB INDEX          1486 non-null   float64
 19  AEX INDEX               1497 non-null   float64
 20  OMX STOCKHOLM INDEX     1471 non-null   float64
 21  SWISS MARKET INDEX      1471 non-null   float64
 22  RTS INDEX               1444 non-null   float64
dtypes: datetime64[ns](1), float64(22)
memory usage: 287.4 KB

In [12]:
data = data.iloc[:1510]

In [13]:
data

,Date,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
0,2022-12-30,3839.50,511646752.0,724693120.0,26094.50,19781.41,3871.63,7038.688,NaN,18105.30,...,3251.32,3793.62,7451.74,6473.76,13923.59,23706.96,689.01,2043.404,10729.40,970.60
1,2022-12-29,3849.28,466689120.0,729421504.0,26093.67,19741.14,3856.70,7020.063,2236.40,18191.00,...,3249.24,3850.07,7512.72,6573.47,14071.72,24056.55,701.01,2075.313,10857.35,936.80
2,2022-12-28,3783.22,438066304.0,740323072.0,26340.50,19898.91,3871.26,7086.407,2280.45,18122.50,...,3266.97,3808.82,7497.19,6510.49,13925.60,23770.44,694.84,2052.762,10812.67,933.76
3,2022-12-27,3829.25,449987360.0,754168384.0,26447.87,NaN,3887.85,NaN,2332.79,18132.30,...,3266.38,3832.89,NaN,6550.66,13995.10,23855.86,701.06,2067.607,10839.22,960.51
4,2022-12-23,3844.82,407580896.0,763465024.0,26235.25,19593.06,3828.22,7107.689,2313.69,17806.80,...,3257.70,3817.01,7473.01,6504.90,13940.93,23877.55,701.06,2054.329,10804.68,963.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2017-01-09,2268.90,532332864.0,541448000.0,NaN,22558.69,3363.90,5807.445,2048.78,8236.05,...,2981.54,3308.97,7237.77,4887.57,11563.99,19360.02,485.10,1509.821,8424.86,1160.27
1506,2017-01-06,2276.98,485214848.0,549549952.0,19454.33,22503.01,3347.67,5755.581,2049.12,8243.80,...,2962.63,3321.17,7210.05,4909.84,11599.01,19687.71,487.00,NaN,8417.46,1172.59
1507,2017-01-05,2269.00,573475776.0,564809856.0,19520.69,22456.69,3367.79,5753.350,2041.95,8273.80,...,2954.14,3316.47,7195.31,4900.64,11584.94,19642.81,486.93,1522.103,8392.49,1180.31
1508,2017-01-04,2270.75,573172224.0,566080832.0,19594.16,22134.47,3368.31,5736.409,2045.64,8190.50,...,2921.31,3317.52,7189.74,4899.40,11584.31,19626.64,487.58,1530.926,8354.81,1176.69
1509,2017-01-03,2257.83,649219392.0,569995712.0,NaN,22150.40,3342.23,5733.183,2043.97,8192.25,...,2898.97,3315.02,7177.89,4899.33,11584.24,19573.48,487.99,1534.697,8316.18,1189.32

In [14]:
#need to check how to handle missing values - Try average return for the day and check. d
data = data.fillna(axis=0,method='bfill')

In [15]:
data

,Date,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
0,2022-12-30,3839.50,511646752.0,724693120.0,26094.50,19781.41,3871.63,7038.688,2236.40,18105.30,...,3251.32,3793.62,7451.74,6473.76,13923.59,23706.96,689.01,2043.404,10729.40,970.60
1,2022-12-29,3849.28,466689120.0,729421504.0,26093.67,19741.14,3856.70,7020.063,2236.40,18191.00,...,3249.24,3850.07,7512.72,6573.47,14071.72,24056.55,701.01,2075.313,10857.35,936.80
2,2022-12-28,3783.22,438066304.0,740323072.0,26340.50,19898.91,3871.26,7086.407,2280.45,18122.50,...,3266.97,3808.82,7497.19,6510.49,13925.60,23770.44,694.84,2052.762,10812.67,933.76
3,2022-12-27,3829.25,449987360.0,754168384.0,26447.87,19593.06,3887.85,7107.689,2332.79,18132.30,...,3266.38,3832.89,7473.01,6550.66,13995.10,23855.86,701.06,2067.607,10839.22,960.51
4,2022-12-23,3844.82,407580896.0,763465024.0,26235.25,19593.06,3828.22,7107.689,2313.69,17806.80,...,3257.70,3817.01,7473.01,6504.90,13940.93,23877.55,701.06,2054.329,10804.68,963.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2017-01-09,2268.90,532332864.0,541448000.0,19454.33,22558.69,3363.90,5807.445,2048.78,8236.05,...,2981.54,3308.97,7237.77,4887.57,11563.99,19360.02,485.10,1509.821,8424.86,1160.27
1506,2017-01-06,2276.98,485214848.0,549549952.0,19454.33,22503.01,3347.67,5755.581,2049.12,8243.80,...,2962.63,3321.17,7210.05,4909.84,11599.01,19687.71,487.00,1522.103,8417.46,1172.59
1507,2017-01-05,2269.00,573475776.0,564809856.0,19520.69,22456.69,3367.79,5753.350,2041.95,8273.80,...,2954.14,3316.47,7195.31,4900.64,11584.94,19642.81,486.93,1522.103,8392.49,1180.31
1508,2017-01-04,2270.75,573172224.0,566080832.0,19594.16,22134.47,3368.31,5736.409,2045.64,8190.50,...,2921.31,3317.52,7189.74,4899.40,11584.31,19626.64,487.58,1530.926,8354.81,1176.69
1509,2017-01-03,2257.83,649219392.0,569995712.0,NaN,22150.40,3342.23,5733.183,2043.97,8192.25,...,2898.97,3315.02,7177.89,4899.33,11584.24,19573.48,487.99,1534.697,8316.18,1189.32

In [16]:
data.isna().sum()

Date                      0
Last Price                0
Volume                    0
SMAVG (15)                0
NIKKEI 225                1
HANG SENG                 0
SHANGHAI                  0
SP ASX 200                0
KOSPI  100                0
NIFTY 50                  0
TAIWAN INDEX              0
JAKARTA COMPOSITE         0
FTSE BURSA MAL TOP 100    0
STRAITS TIMES             0
EURO STOXX 50 PR          0
FTSE 100 INDEX            0
CAC 40 INDEX              0
DAX INDEX                 0
FTSE MIB INDEX            0
AEX INDEX                 0
OMX STOCKHOLM INDEX       0
SWISS MARKET INDEX        0
RTS INDEX                 0
dtype: int64

In [17]:
data = data.fillna(axis=0,method='ffill')
data.isna().sum()

Date                      0
Last Price                0
Volume                    0
SMAVG (15)                0
NIKKEI 225                0
HANG SENG                 0
SHANGHAI                  0
SP ASX 200                0
KOSPI  100                0
NIFTY 50                  0
TAIWAN INDEX              0
JAKARTA COMPOSITE         0
FTSE BURSA MAL TOP 100    0
STRAITS TIMES             0
EURO STOXX 50 PR          0
FTSE 100 INDEX            0
CAC 40 INDEX              0
DAX INDEX                 0
FTSE MIB INDEX            0
AEX INDEX                 0
OMX STOCKHOLM INDEX       0
SWISS MARKET INDEX        0
RTS INDEX                 0
dtype: int64

In [18]:
data = data.loc[::-1].reset_index(drop=True)

In [19]:
data

,Date,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
0,2017-01-03,2257.83,649219392.0,569995712.0,19594.16,22150.40,3342.23,5733.183,2043.97,8192.25,...,2898.97,3315.02,7177.89,4899.33,11584.24,19573.48,487.99,1534.697,8316.18,1189.32
1,2017-01-04,2270.75,573172224.0,566080832.0,19594.16,22134.47,3368.31,5736.409,2045.64,8190.50,...,2921.31,3317.52,7189.74,4899.40,11584.31,19626.64,487.58,1530.926,8354.81,1176.69
2,2017-01-05,2269.00,573475776.0,564809856.0,19520.69,22456.69,3367.79,5753.350,2041.95,8273.80,...,2954.14,3316.47,7195.31,4900.64,11584.94,19642.81,486.93,1522.103,8392.49,1180.31
3,2017-01-06,2276.98,485214848.0,549549952.0,19454.33,22503.01,3347.67,5755.581,2049.12,8243.80,...,2962.63,3321.17,7210.05,4909.84,11599.01,19687.71,487.00,1522.103,8417.46,1172.59
4,2017-01-09,2268.90,532332864.0,541448000.0,19454.33,22558.69,3363.90,5807.445,2048.78,8236.05,...,2981.54,3308.97,7237.77,4887.57,11563.99,19360.02,485.10,1509.821,8424.86,1160.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2022-12-23,3844.82,407580896.0,763465024.0,26235.25,19593.06,3828.22,7107.689,2313.69,17806.80,...,3257.70,3817.01,7473.01,6504.90,13940.93,23877.55,701.06,2054.329,10804.68,963.51
1506,2022-12-27,3829.25,449987360.0,754168384.0,26447.87,19593.06,3887.85,7107.689,2332.79,18132.30,...,3266.38,3832.89,7473.01,6550.66,13995.10,23855.86,701.06,2067.607,10839.22,960.51
1507,2022-12-28,3783.22,438066304.0,740323072.0,26340.50,19898.91,3871.26,7086.407,2280.45,18122.50,...,3266.97,3808.82,7497.19,6510.49,13925.60,23770.44,694.84,2052.762,10812.67,933.76
1508,2022-12-29,3849.28,466689120.0,729421504.0,26093.67,19741.14,3856.70,7020.063,2236.40,18191.00,...,3249.24,3850.07,7512.72,6573.47,14071.72,24056.55,701.01,2075.313,10857.35,936.80
1509,2022-12-30,3839.50,511646752.0,724693120.0,26094.50,19781.41,3871.63,7038.688,2236.40,18105.30,...,3251.32,3793.62,7451.74,6473.76,13923.59,23706.96,689.01,2043.404,10729.40,970.60

In [20]:
#data.loc[:,'Last Price':'NIKKEI 225'].plot()

In [21]:
data.describe()

,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
count,1510.000000,1.510000e+03,1.510000e+03,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,...,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000
mean,3283.396099,6.226080e+08,6.219603e+08,23833.936404,25902.747119,4106.492609,6428.518024,2433.146550,12695.636623,12703.881358,...,3137.447695,3560.450013,7044.928457,5643.095656,13038.831265,22150.588616,603.758106,1800.028485,10123.783576,1267.120755
std,716.844076,2.289733e+08,1.184628e+08,3369.665874,3343.109238,609.263980,611.691017,370.567377,3012.804337,2795.772089,...,252.584167,333.560180,829.023115,675.914350,1403.316352,2404.832509,91.042906,277.309324,1197.315275,209.600607
min,2237.400000,1.707938e+08,4.333132e+08,16552.830000,14687.020000,2964.840000,4546.035000,1457.640000,7610.250000,8681.340000,...,2233.480000,2385.820000,0.000000,3754.840000,8441.710000,14894.440000,404.100000,1292.274000,8160.790000,742.910000
25%,2712.177500,5.077853e+08,5.441998e+08,21301.960000,24223.697500,3712.455000,5905.950750,2155.175000,10458.462500,10529.970000,...,3087.630000,3361.162500,6981.610000,5161.262500,12169.852500,20575.427500,536.637500,1580.506000,9035.292500,1122.992500
50%,3005.585000,5.716708e+08,5.941790e+08,22820.175000,26284.110000,3958.590000,6322.962500,2363.670000,11498.400000,11164.390000,...,3190.605000,3515.455000,7249.180000,5481.570000,12817.655000,21985.320000,565.170000,1670.744000,9991.365000,1207.845000
75%,3916.182500,6.654106e+08,6.845549e+08,27249.927500,28395.697500,4635.305000,6964.352250,2612.040000,15726.475000,15210.510000,...,3267.935000,3737.795000,7445.572500,6131.355000,13810.257500,23829.917500,680.202500,1998.445000,10970.040000,1398.682500
max,4796.560000,2.480939e+09,1.266652e+09,30670.100000,33154.120000,5807.720000,7628.923000,3305.210000,18812.500000,18526.350000,...,3615.280000,4401.490000,7877.450000,7376.370000,16271.750000,28162.670000,827.570000,2456.172000,12970.530000,1919.580000

In [22]:
data.corr()

C:\Users\suraj\AppData\Local\Temp\ipykernel_11620\2627137660.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()

,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
Last Price,1.000000,0.048749,0.104336,0.933653,-0.367720,0.741237,0.889699,0.742695,0.935200,0.971734,...,-0.051142,0.743784,-0.006556,0.858435,0.838028,0.716846,0.960342,0.953373,0.962586,0.569565
Volume,0.048749,1.000000,0.483014,0.022933,-0.176532,0.019254,-0.077702,-0.066080,0.046433,0.050929,...,-0.206999,-0.167173,-0.134294,-0.078603,-0.115679,-0.137537,-0.025326,-0.009638,0.021040,-0.107816
SMAVG (15),0.104336,0.483014,1.000000,0.033677,-0.351034,0.032744,-0.162217,-0.136508,0.081006,0.091647,...,-0.418973,-0.322657,-0.292462,-0.156642,-0.220639,-0.270082,-0.033489,-0.009188,0.055857,-0.239575
NIKKEI 225,0.933653,0.022933,0.033677,1.000000,-0.240860,0.748537,0.856430,0.814400,0.912995,0.925766,...,0.065085,0.755131,0.059872,0.840626,0.850023,0.736393,0.927756,0.914164,0.860423,0.565160
HANG SENG,-0.367720,-0.176532,-0.351034,-0.240860,1.000000,0.093288,-0.242701,0.120672,-0.480866,-0.290029,...,0.299759,-0.030629,0.103537,-0.253765,-0.061654,0.055743,-0.304078,-0.285734,-0.341236,0.247417
SHANGHAI,0.741237,0.019254,0.032744,0.748537,0.093288,1.000000,0.584358,0.797388,0.562769,0.787771,...,-0.240390,0.575026,-0.160337,0.516194,0.735635,0.553310,0.679700,0.763583,0.727807,0.650480
SP ASX 200,0.889699,-0.077702,-0.162217,0.856430,-0.242701,0.584358,1.000000,0.665495,0.886592,0.852235,...,0.236543,0.843370,0.188790,0.932221,0.841788,0.824028,0.923077,0.874629,0.897950,0.623641
KOSPI 100,0.742695,-0.066080,-0.136508,0.814400,0.120672,0.797388,0.665495,1.000000,0.654361,0.835953,...,0.176153,0.792441,0.080634,0.704353,0.883329,0.765405,0.781982,0.836095,0.688725,0.587507
NIFTY 50,0.935200,0.046433,0.081006,0.912995,-0.480866,0.562769,0.886592,0.654361,1.000000,0.897259,...,0.131091,0.730643,0.105799,0.892813,0.771999,0.717915,0.940527,0.884536,0.878231,0.432126
TAIWAN INDEX,0.971734,0.050929,0.091647,0.925766,-0.290029,0.787771,0.852235,0.835953,0.897259,1.000000,...,-0.000787,0.776850,0.007317,0.847281,0.876544,0.747164,0.946785,0.963063,0.932636,0.552974
JAKARTA COMPOSITE,0.484797,-0.064249,-0.147597,0.541219,-0.217175,0.084857,0.644937,0.337651,0.689626,0.459022,...,0.666515,0.543131,0.381875,0.701862,0.435659,0.610694,0.571937,0.421444,0.446256,0.143595
FTSE BURSA MAL TOP 100,-0.486475,-0.262281,-0.521631,-0.329477,0.687607,-0.242729,-0.309624,0.065083,-0.456916,-0.384843,...,0.571571,0.016302,0.289189,-0.213279,-0.076192,0.062392,-0.355363,-0.362043,-0.498695,-0.117951
STRAITS TIMES,-0.051142,-0.206999,-0.418973,0.065085,0.299759,-0.240390,0.236543,0.176153,0.131091,-0.000787,...,1.000000,0.423527,0.556502,0.391846,0.225499,0.511616,0.149188,0.018062,-0.046825,0.005552
EURO STOXX 50 PR,0.743784,-0.167173,-0.322657,0.755131,-0.030629,0.575026,0.843370,0.792441,0.730643,0.776850,...,0.423527,1.000000,0.301345,0.932490,0.955606,0.959913,0.872579,0.859321,0.775957,0.649234
FTSE 100 INDEX,-0.006556,-0.134294,-0.292462,0.059872,0.103537,-0.160337,0.188790,0.080634,0.105799,0.007317,...,0.556502,0.301345,1.000000,0.282286,0.168571,0.323127,0.125501,0.045290,0.008201,0.042475
CAC 40 INDEX,0.858435,-0.078603,-0.156642,0.840626,-0.253765,0.516194,0.932221,0.704353,0.892813,0.847281,...,0.391846,0.932490,0.282286,1.000000,0.895413,0.918836,0.946204,0.888249,0.862540,0.558523
DAX INDEX,0.838028,-0.115679,-0.220639,0.850023,-0.061654,0.735635,0.841788,0.883329,0.771999,0.876544,...,0.225499,0.955606,0.168571,0.895413,1.000000,0.909330,0.909768,0.932770,0.844216,0.667429
FTSE MIB INDEX,0.716846,-0.137537,-0.270082,0.736393,0.055743,0.553310,0.824028,0.765405,0.717915,0.747164,...,0.511616,0.959913,0.323127,0.918836,0.909330,1.000000,0.841864,0.798608,0.743423,0.628875
AEX INDEX,0.960342,-0.025326,-0.033489,0.927756,-0.304078,0.679700,0.923077,0.781982,0.940527,0.946785,...,0.149188,0.872579,0.125501,0.946204,0.909768,0.841864,1.000000,0.964413,0.938119,0.619022
OMX STOCKHOLM INDEX,0.953373,-0.009638,-0.009188,0.914164,-0.285734,0.763583,0.874629,0.836095,0.884536,0.963063,...,0.018062,0.859321,0.045290,0.888249,0.932770,0.798608,0.964413,1.000000,0.937839,0.629955
SWISS MARKET INDEX,0.962586,0.021040,0.055857,0.860423,-0.341236,0.727807,0.897950,0.688725,0.878231,0.932636,...,-0.046825,0.775957,0.008201,0.862540,0.844216,0.743423,0.938119,0.937839,1.000000,0.612714
RTS INDEX,0.569565,-0.107816,-0.239575,0.565160,0.247417,0.650480,0.623641,0.587507,0.432126,0.552974,...,0.005552,0.649234,0.042475,0.558523,0.667429,0.628875,0.619022,0.629955,0.612714,1.000000

In [23]:
data['% Change'] = data['Last Price'].pct_change()*100

In [24]:
data['Direction'] = [1 if i>0 else 0 for i in data['% Change']]

In [25]:
data

,Date,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,...,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX,% Change,Direction
0,2017-01-03,2257.83,649219392.0,569995712.0,19594.16,22150.40,3342.23,5733.183,2043.97,8192.25,...,7177.89,4899.33,11584.24,19573.48,487.99,1534.697,8316.18,1189.32,NaN,0
1,2017-01-04,2270.75,573172224.0,566080832.0,19594.16,22134.47,3368.31,5736.409,2045.64,8190.50,...,7189.74,4899.40,11584.31,19626.64,487.58,1530.926,8354.81,1176.69,0.572231,1
2,2017-01-05,2269.00,573475776.0,564809856.0,19520.69,22456.69,3367.79,5753.350,2041.95,8273.80,...,7195.31,4900.64,11584.94,19642.81,486.93,1522.103,8392.49,1180.31,-0.077067,0
3,2017-01-06,2276.98,485214848.0,549549952.0,19454.33,22503.01,3347.67,5755.581,2049.12,8243.80,...,7210.05,4909.84,11599.01,19687.71,487.00,1522.103,8417.46,1172.59,0.351697,1
4,2017-01-09,2268.90,532332864.0,541448000.0,19454.33,22558.69,3363.90,5807.445,2048.78,8236.05,...,7237.77,4887.57,11563.99,19360.02,485.10,1509.821,8424.86,1160.27,-0.354856,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2022-12-23,3844.82,407580896.0,763465024.0,26235.25,19593.06,3828.22,7107.689,2313.69,17806.80,...,7473.01,6504.90,13940.93,23877.55,701.06,2054.329,10804.68,963.51,0.586806,1
1506,2022-12-27,3829.25,449987360.0,754168384.0,26447.87,19593.06,3887.85,7107.689,2332.79,18132.30,...,7473.01,6550.66,13995.10,23855.86,701.06,2067.607,10839.22,960.51,-0.404960,0
1507,2022-12-28,3783.22,438066304.0,740323072.0,26340.50,19898.91,3871.26,7086.407,2280.45,18122.50,...,7497.19,6510.49,13925.60,23770.44,694.84,2052.762,10812.67,933.76,-1.202063,0
1508,2022-12-29,3849.28,466689120.0,729421504.0,26093.67,19741.14,3856.70,7020.063,2236.40,18191.00,...,7512.72,6573.47,14071.72,24056.55,701.01,2075.313,10857.35,936.80,1.746132,1
1509,2022-12-30,3839.50,511646752.0,724693120.0,26094.50,19781.41,3871.63,7038.688,2236.40,18105.30,...,7451.74,6473.76,13923.59,23706.96,689.01,2043.404,10729.40,970.60,-0.254073,0

In [26]:
# shifting the direction so that we can use it to predict the next day movement. 
#data['Direction'] = data['Direction'].shift(-1, fill_value=0)
#data

In [27]:
data = data.dropna()

In [28]:
data.isnull().sum()

Date                      0
Last Price                0
Volume                    0
SMAVG (15)                0
NIKKEI 225                0
HANG SENG                 0
SHANGHAI                  0
SP ASX 200                0
KOSPI  100                0
NIFTY 50                  0
TAIWAN INDEX              0
JAKARTA COMPOSITE         0
FTSE BURSA MAL TOP 100    0
STRAITS TIMES             0
EURO STOXX 50 PR          0
FTSE 100 INDEX            0
CAC 40 INDEX              0
DAX INDEX                 0
FTSE MIB INDEX            0
AEX INDEX                 0
OMX STOCKHOLM INDEX       0
SWISS MARKET INDEX        0
RTS INDEX                 0
% Change                  0
Direction                 0
dtype: int64

In [29]:
df = data.copy()

In [30]:
X = df.loc[:,'Volume':'RTS INDEX']
X

,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
1,573172224.0,566080832.0,19594.16,22134.47,3368.31,5736.409,2045.64,8190.50,9286.96,5301.183,...,2921.31,3317.52,7189.74,4899.40,11584.31,19626.64,487.58,1530.926,8354.81,1176.69
2,573475776.0,564809856.0,19520.69,22456.69,3367.79,5753.350,2041.95,8273.80,9358.14,5325.504,...,2954.14,3316.47,7195.31,4900.64,11584.94,19642.81,486.93,1522.103,8392.49,1180.31
3,485214848.0,549549952.0,19454.33,22503.01,3347.67,5755.581,2049.12,8243.80,9372.22,5347.022,...,2962.63,3321.17,7210.05,4909.84,11599.01,19687.71,487.00,1522.103,8417.46,1172.59
4,532332864.0,541448000.0,19454.33,22558.69,3363.90,5807.445,2048.78,8236.05,9342.42,5316.364,...,2981.54,3308.97,7237.77,4887.57,11563.99,19360.02,485.10,1509.821,8424.86,1160.27
5,596464384.0,481377280.0,19301.44,22744.85,3358.27,5760.702,2045.12,8288.60,9349.64,5309.924,...,3006.02,3306.21,7275.47,4888.23,11583.30,19424.19,484.74,1510.092,8449.19,1175.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,407580896.0,763465024.0,26235.25,19593.06,3828.22,7107.689,2313.69,17806.80,14271.63,6800.673,...,3257.70,3817.01,7473.01,6504.90,13940.93,23877.55,701.06,2054.329,10804.68,963.51
1506,449987360.0,754168384.0,26447.87,19593.06,3887.85,7107.689,2332.79,18132.30,14328.43,6923.027,...,3266.38,3832.89,7473.01,6550.66,13995.10,23855.86,701.06,2067.607,10839.22,960.51
1507,438066304.0,740323072.0,26340.50,19898.91,3871.26,7086.407,2280.45,18122.50,14173.10,6850.520,...,3266.97,3808.82,7497.19,6510.49,13925.60,23770.44,694.84,2052.762,10812.67,933.76
1508,466689120.0,729421504.0,26093.67,19741.14,3856.70,7020.063,2236.40,18191.00,14085.02,6860.077,...,3249.24,3850.07,7512.72,6573.47,14071.72,24056.55,701.01,2075.313,10857.35,936.80
1509,511646752.0,724693120.0,26094.50,19781.41,3871.63,7038.688,2236.40,18105.30,14137.69,6850.619,...,3251.32,3793.62,7451.74,6473.76,13923.59,23706.96,689.01,2043.404,10729.40,970.60

In [31]:
y = df['Direction']
y

1       1
2       0
3       1
4       0
5       0
       ..
1505    1
1506    0
1507    0
1508    1
1509    0
Name: Direction, Length: 1509, dtype: int64

In [32]:
# splitting test train 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state = 21, shuffle = False)
X_train.tail()

,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
1052,670320896.0,718274816.0,29036.56,28907.52,5003.61,6714.105,2958.12,15174.80,15911.67,6264.679,...,3079.72,3819.92,6725.60,5990.55,14540.25,23925.96,678.03,2134.464,10909.77,1479.57
1053,633849728.0,725838272.0,29211.64,29385.61,5128.22,6713.922,3013.70,15174.80,16179.56,6264.679,...,3106.01,3845.64,6736.96,6033.76,14569.39,24121.37,683.71,2165.660,10883.23,1505.22
1054,590613504.0,720862848.0,29717.83,28739.72,5146.38,6766.811,3054.39,15030.95,16255.18,6358.209,...,3095.22,3833.36,6761.47,6046.55,14502.39,24113.22,677.41,2168.962,10839.93,1519.50
1055,599944960.0,714722432.0,29766.97,28833.76,5035.54,6773.013,3045.71,14929.50,16249.33,6324.259,...,3106.00,3829.84,6749.70,6035.97,14461.42,24139.45,678.80,2161.828,10867.33,1543.99
1056,606621312.0,704796288.0,29921.09,29027.69,5079.36,6827.136,3067.17,14910.45,16313.16,6309.699,...,3105.51,3850.96,6803.61,6055.43,14557.58,24261.12,683.65,2180.141,10944.48,1552.81

In [33]:
from sklearn.preprocessing import StandardScaler
log_reg = LogisticRegression(random_state=0, tol=1e-8, max_iter=5000, class_weight = 'balanced').fit(X_train, y_train)

In [34]:
log_reg.predict(X_test)

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [35]:
log_reg.score(X_train, y_train)

0.5596590909090909

In [36]:
log_reg.score(X_test, y_test)

0.543046357615894

In [37]:
from sklearn.svm import SVC

In [38]:
model = SVC()
model.fit(X_train,y_train)
pred = model.predict(X_test)

In [39]:
model.score(X_train, y_train)

0.5691287878787878

In [40]:
model.score(X_test, y_test)

0.4922737306843267

In [41]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, pred)
cnf_matrix

array([[  9, 221],
       [  9, 214]], dtype=int64)

In [42]:
model = SVC(kernel='rbf', C=1e3, gamma=0.1)
model.fit(X_train,y_train)
pred = model.predict(X_test)

In [43]:
model.score(X_train, y_train)

1.0

In [44]:
model.score(X_test, y_test)

0.4922737306843267

In [45]:
X

,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
1,573172224.0,566080832.0,19594.16,22134.47,3368.31,5736.409,2045.64,8190.50,9286.96,5301.183,...,2921.31,3317.52,7189.74,4899.40,11584.31,19626.64,487.58,1530.926,8354.81,1176.69
2,573475776.0,564809856.0,19520.69,22456.69,3367.79,5753.350,2041.95,8273.80,9358.14,5325.504,...,2954.14,3316.47,7195.31,4900.64,11584.94,19642.81,486.93,1522.103,8392.49,1180.31
3,485214848.0,549549952.0,19454.33,22503.01,3347.67,5755.581,2049.12,8243.80,9372.22,5347.022,...,2962.63,3321.17,7210.05,4909.84,11599.01,19687.71,487.00,1522.103,8417.46,1172.59
4,532332864.0,541448000.0,19454.33,22558.69,3363.90,5807.445,2048.78,8236.05,9342.42,5316.364,...,2981.54,3308.97,7237.77,4887.57,11563.99,19360.02,485.10,1509.821,8424.86,1160.27
5,596464384.0,481377280.0,19301.44,22744.85,3358.27,5760.702,2045.12,8288.60,9349.64,5309.924,...,3006.02,3306.21,7275.47,4888.23,11583.30,19424.19,484.74,1510.092,8449.19,1175.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,407580896.0,763465024.0,26235.25,19593.06,3828.22,7107.689,2313.69,17806.80,14271.63,6800.673,...,3257.70,3817.01,7473.01,6504.90,13940.93,23877.55,701.06,2054.329,10804.68,963.51
1506,449987360.0,754168384.0,26447.87,19593.06,3887.85,7107.689,2332.79,18132.30,14328.43,6923.027,...,3266.38,3832.89,7473.01,6550.66,13995.10,23855.86,701.06,2067.607,10839.22,960.51
1507,438066304.0,740323072.0,26340.50,19898.91,3871.26,7086.407,2280.45,18122.50,14173.10,6850.520,...,3266.97,3808.82,7497.19,6510.49,13925.60,23770.44,694.84,2052.762,10812.67,933.76
1508,466689120.0,729421504.0,26093.67,19741.14,3856.70,7020.063,2236.40,18191.00,14085.02,6860.077,...,3249.24,3850.07,7512.72,6573.47,14071.72,24056.55,701.01,2075.313,10857.35,936.80
1509,511646752.0,724693120.0,26094.50,19781.41,3871.63,7038.688,2236.40,18105.30,14137.69,6850.619,...,3251.32,3793.62,7451.74,6473.76,13923.59,23706.96,689.01,2043.404,10729.40,970.60

In [46]:
X = X.diff()
X

,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,303552.0,-1270976.0,-73.47,322.22,-0.52,16.941,-3.69,83.30,71.18,24.321,...,32.83,-1.05,5.57,1.24,0.63,16.17,-0.65,-8.823,37.68,3.62
3,-88260928.0,-15259904.0,-66.36,46.32,-20.12,2.231,7.17,-30.00,14.08,21.518,...,8.49,4.70,14.74,9.20,14.07,44.90,0.07,0.000,24.97,-7.72
4,47118016.0,-8101952.0,0.00,55.68,16.23,51.864,-0.34,-7.75,-29.80,-30.658,...,18.91,-12.20,27.72,-22.27,-35.02,-327.69,-1.90,-12.282,7.40,-12.32
5,64131520.0,-60070720.0,-152.89,186.16,-5.63,-46.743,-3.66,52.55,7.22,-6.440,...,24.48,-2.76,37.70,0.66,19.31,64.17,-0.36,0.271,24.33,14.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,-211597216.0,-9440128.0,-272.62,-86.16,-7.81,-44.811,-43.04,-320.55,-171.31,-23.759,...,-11.83,-6.28,3.73,-13.07,26.86,64.25,0.66,11.032,30.04,-6.19
1506,42406464.0,-9296640.0,212.62,0.00,59.63,0.000,19.10,325.50,56.80,122.354,...,8.68,15.88,0.00,45.76,54.17,-21.69,0.00,13.278,34.54,-3.00
1507,-11921056.0,-13845312.0,-107.37,305.85,-16.59,-21.282,-52.34,-9.80,-155.33,-72.507,...,0.59,-24.07,24.18,-40.17,-69.50,-85.42,-6.22,-14.845,-26.55,-26.75
1508,28622816.0,-10901568.0,-246.83,-157.77,-14.56,-66.344,-44.05,68.50,-88.08,9.557,...,-17.73,41.25,15.53,62.98,146.12,286.11,6.17,22.551,44.68,3.04
1509,44957632.0,-4728384.0,0.83,40.27,14.93,18.625,0.00,-85.70,52.67,-9.458,...,2.08,-56.45,-60.98,-99.71,-148.13,-349.59,-12.00,-31.909,-127.95,33.80

In [47]:
X = X.dropna()
X

,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
2,303552.0,-1270976.0,-73.47,322.22,-0.52,16.941,-3.69,83.30,71.18,24.321,...,32.83,-1.05,5.57,1.24,0.63,16.17,-0.65,-8.823,37.68,3.62
3,-88260928.0,-15259904.0,-66.36,46.32,-20.12,2.231,7.17,-30.00,14.08,21.518,...,8.49,4.70,14.74,9.20,14.07,44.90,0.07,0.000,24.97,-7.72
4,47118016.0,-8101952.0,0.00,55.68,16.23,51.864,-0.34,-7.75,-29.80,-30.658,...,18.91,-12.20,27.72,-22.27,-35.02,-327.69,-1.90,-12.282,7.40,-12.32
5,64131520.0,-60070720.0,-152.89,186.16,-5.63,-46.743,-3.66,52.55,7.22,-6.440,...,24.48,-2.76,37.70,0.66,19.31,64.17,-0.36,0.271,24.33,14.74
6,-46996800.0,3085056.0,63.23,190.50,-23.77,10.780,30.05,92.05,-3.90,-8.687,...,-5.08,1.73,15.02,0.48,62.87,62.69,1.84,1.784,-22.04,-19.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,-211597216.0,-9440128.0,-272.62,-86.16,-7.81,-44.811,-43.04,-320.55,-171.31,-23.759,...,-11.83,-6.28,3.73,-13.07,26.86,64.25,0.66,11.032,30.04,-6.19
1506,42406464.0,-9296640.0,212.62,0.00,59.63,0.000,19.10,325.50,56.80,122.354,...,8.68,15.88,0.00,45.76,54.17,-21.69,0.00,13.278,34.54,-3.00
1507,-11921056.0,-13845312.0,-107.37,305.85,-16.59,-21.282,-52.34,-9.80,-155.33,-72.507,...,0.59,-24.07,24.18,-40.17,-69.50,-85.42,-6.22,-14.845,-26.55,-26.75
1508,28622816.0,-10901568.0,-246.83,-157.77,-14.56,-66.344,-44.05,68.50,-88.08,9.557,...,-17.73,41.25,15.53,62.98,146.12,286.11,6.17,22.551,44.68,3.04
1509,44957632.0,-4728384.0,0.83,40.27,14.93,18.625,0.00,-85.70,52.67,-9.458,...,2.08,-56.45,-60.98,-99.71,-148.13,-349.59,-12.00,-31.909,-127.95,33.80

In [48]:
y = y.loc[2:,]
y

2       0
3       1
4       0
5       0
6       1
       ..
1505    1
1506    0
1507    0
1508    1
1509    0
Name: Direction, Length: 1508, dtype: int64

In [49]:
# splitting test train 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state = 21, shuffle = False)
X_train.head()

,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
2,303552.0,-1270976.0,-73.47,322.22,-0.52,16.941,-3.69,83.30,71.18,24.321,...,32.83,-1.05,5.57,1.24,0.63,16.17,-0.65,-8.823,37.68,3.62
3,-88260928.0,-15259904.0,-66.36,46.32,-20.12,2.231,7.17,-30.00,14.08,21.518,...,8.49,4.70,14.74,9.20,14.07,44.90,0.07,0.000,24.97,-7.72
4,47118016.0,-8101952.0,0.00,55.68,16.23,51.864,-0.34,-7.75,-29.80,-30.658,...,18.91,-12.20,27.72,-22.27,-35.02,-327.69,-1.90,-12.282,7.40,-12.32
5,64131520.0,-60070720.0,-152.89,186.16,-5.63,-46.743,-3.66,52.55,7.22,-6.440,...,24.48,-2.76,37.70,0.66,19.31,64.17,-0.36,0.271,24.33,14.74
6,-46996800.0,3085056.0,63.23,190.50,-23.77,10.780,30.05,92.05,-3.90,-8.687,...,-5.08,1.73,15.02,0.48,62.87,62.69,1.84,1.784,-22.04,-19.51

In [50]:
#Normalising the data set ie (0,1)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [51]:
X_test_scaled = scaler.transform(X_test)

In [52]:
model = SVC(kernel='rbf', C=1, gamma='scale',coef0=0.001, degree = 3)
model.fit(X_train_scaled,y_train)
pred = model.predict(X_test_scaled)

In [53]:
print ("Train Accuracy Score:",model.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",model.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 0.785781990521327
Test Accuracy Score: 0.6821192052980133
Confusion Matrix: [[134  96]
 [ 48 175]]

In [54]:
log_reg = LogisticRegression(random_state=0, tol=1e-8, max_iter=5000, class_weight = 'balanced').fit(X_train_scaled, y_train)

In [55]:
pred = log_reg.predict(X_test_scaled)
print ("Train Accuracy Score:",log_reg.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",log_reg.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 0.7260663507109004
Test Accuracy Score: 0.6644591611479028
Confusion Matrix: [[147  83]
 [ 69 154]]

In [56]:
from sklearn.ensemble import RandomForestClassifier

In [57]:
Rf = RandomForestClassifier(random_state=0)
Rf.fit(X_train_scaled, y_train)
pred = Rf.predict(X_test_scaled)
print ("Train Accuracy Score:",Rf.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",Rf.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 1.0
Test Accuracy Score: 0.6821192052980133
Confusion Matrix: [[134  96]
 [ 48 175]]

In [58]:
from sklearn.ensemble import GradientBoostingClassifier

In [59]:
GB = GradientBoostingClassifier()
GB.fit(X_train_scaled, y_train)
pred = GB.predict(X_test_scaled)
print ("Train Accuracy Score:",GB.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",GB.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 0.8909952606635071
Test Accuracy Score: 0.6843267108167771
Confusion Matrix: [[144  86]
 [ 57 166]]

In [60]:
#pip install xgboost

In [61]:
from sklearn.pipeline import Pipeline 
from xgboost import XGBClassifier 

estimator = [
    #'encoder', TargetEncoder()),
    ('clf', XGBClassifier(random_state=8))
  
]

pipe = Pipeline(steps= estimator)
pipe

Pipeline(steps=[('clf',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, gpu_id=None,
                               grow_policy=None, importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, n_estimators=100,
                               n_jobs=None, num_parallel_tree=None,
                               predictor=None, random_state=8, ...))])

In [62]:
#pip install scikit-optimize

In [63]:
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer

In [64]:
search_space = {
    'clf__max_depth': Integer(2,8),
    'clf__learning_rate': Real(0.001,1.0, prior = 'log-uniform'),
    'clf__subsample': Real(0.5, 1.0),
    'clf__colsample_bytree': Real(0.5, 1.0),
    'clf__colsample_bylevel': Real(0.5, 1.0),
    'clf__colsample_bynode': Real(0.5, 1.0),
    'clf__reg_alpha': Real(0.0, 10.0),
    'clf__reg_lambda': Real(0.0, 10.0),
    'clf__gamma': Real(0.0, 10.0),
}

opt = BayesSearchCV(pipe, search_space, cv=3, n_iter=10, scoring='roc_auc', random_state = 8)

In [65]:
opt.fit(X_train_scaled, y_train)

BayesSearchCV(cv=3,
              estimator=Pipeline(steps=[('clf',
                                         XGBClassifier(base_score=None,
                                                       booster=None,
                                                       callbacks=None,
                                                       colsample_bylevel=None,
                                                       colsample_bynode=None,
                                                       colsample_bytree=None,
                                                       early_stopping_rounds=None,
                                                       enable_categorical=False,
                                                       eval_metric=None,
                                                       feature_types=None,
                                                       gamma=None, gpu_id=None,
                                                       grow_policy=None,
                                                       importance_type=None,
                                                       interaction_constraints=...
                             'clf__learning_rate': Real(low=0.001, high=1.0, prior='log-uniform', transform='normalize'),
                             'clf__max_depth': Integer(low=2, high=8, prior='uniform', transform='normalize'),
                             'clf__reg_alpha': Real(low=0.0, high=10.0, prior='uniform', transform='normalize'),
                             'clf__reg_lambda': Real(low=0.0, high=10.0, prior='uniform', transform='normalize'),
                             'clf__subsample': Real(low=0.5, high=1.0, prior='uniform', transform='normalize')})

In [66]:
opt.best_estimator_

Pipeline(steps=[('clf',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=0.7098720980049984,
                               colsample_bynode=0.5395172405909037,
                               colsample_bytree=0.5048675793234745,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=3.4426412862156925,
                               gpu_id=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None,
                               learning_rate=0.002566198468819385, max_bin=None,
                               max_cat_threshold=None, max_cat_to_onehot=None,
                               max_delta_step=None, max_depth=4,
                               max_leaves=None, min_child_weight=None,
                               missing=nan, monotone_constraints=None,
                               n_estimators=100, n_jobs=None,
                               num_parallel_tree=None, predictor=None,
                               random_state=8, ...))])

In [67]:
print ("Train Accuracy Score:",opt.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",opt.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 0.808099749967101
Test Accuracy Score: 0.753948138038604
Confusion Matrix: [[144  86]
 [ 57 166]]

# Try to shift the prediction the next day.

In [68]:
X

,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,...,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
2,303552.0,-1270976.0,-73.47,322.22,-0.52,16.941,-3.69,83.30,71.18,24.321,...,32.83,-1.05,5.57,1.24,0.63,16.17,-0.65,-8.823,37.68,3.62
3,-88260928.0,-15259904.0,-66.36,46.32,-20.12,2.231,7.17,-30.00,14.08,21.518,...,8.49,4.70,14.74,9.20,14.07,44.90,0.07,0.000,24.97,-7.72
4,47118016.0,-8101952.0,0.00,55.68,16.23,51.864,-0.34,-7.75,-29.80,-30.658,...,18.91,-12.20,27.72,-22.27,-35.02,-327.69,-1.90,-12.282,7.40,-12.32
5,64131520.0,-60070720.0,-152.89,186.16,-5.63,-46.743,-3.66,52.55,7.22,-6.440,...,24.48,-2.76,37.70,0.66,19.31,64.17,-0.36,0.271,24.33,14.74
6,-46996800.0,3085056.0,63.23,190.50,-23.77,10.780,30.05,92.05,-3.90,-8.687,...,-5.08,1.73,15.02,0.48,62.87,62.69,1.84,1.784,-22.04,-19.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,-211597216.0,-9440128.0,-272.62,-86.16,-7.81,-44.811,-43.04,-320.55,-171.31,-23.759,...,-11.83,-6.28,3.73,-13.07,26.86,64.25,0.66,11.032,30.04,-6.19
1506,42406464.0,-9296640.0,212.62,0.00,59.63,0.000,19.10,325.50,56.80,122.354,...,8.68,15.88,0.00,45.76,54.17,-21.69,0.00,13.278,34.54,-3.00
1507,-11921056.0,-13845312.0,-107.37,305.85,-16.59,-21.282,-52.34,-9.80,-155.33,-72.507,...,0.59,-24.07,24.18,-40.17,-69.50,-85.42,-6.22,-14.845,-26.55,-26.75
1508,28622816.0,-10901568.0,-246.83,-157.77,-14.56,-66.344,-44.05,68.50,-88.08,9.557,...,-17.73,41.25,15.53,62.98,146.12,286.11,6.17,22.551,44.68,3.04
1509,44957632.0,-4728384.0,0.83,40.27,14.93,18.625,0.00,-85.70,52.67,-9.458,...,2.08,-56.45,-60.98,-99.71,-148.13,-349.59,-12.00,-31.909,-127.95,33.80

In [69]:
X_1 = X.loc[:,'NIKKEI 225':'RTS INDEX']
X_1

,NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,FTSE BURSA MAL TOP 100,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
2,-73.47,322.22,-0.52,16.941,-3.69,83.30,71.18,24.321,78.52,32.83,-1.05,5.57,1.24,0.63,16.17,-0.65,-8.823,37.68,3.62
3,-66.36,46.32,-20.12,2.231,7.17,-30.00,14.08,21.518,81.68,8.49,4.70,14.74,9.20,14.07,44.90,0.07,0.000,24.97,-7.72
4,0.00,55.68,16.23,51.864,-0.34,-7.75,-29.80,-30.658,-44.03,18.91,-12.20,27.72,-22.27,-35.02,-327.69,-1.90,-12.282,7.40,-12.32
5,-152.89,186.16,-5.63,-46.743,-3.66,52.55,7.22,-6.440,27.71,24.48,-2.76,37.70,0.66,19.31,64.17,-0.36,0.271,24.33,14.74
6,63.23,190.50,-23.77,10.780,30.05,92.05,-3.90,-8.687,34.15,-5.08,1.73,15.02,0.48,62.87,62.69,1.84,1.784,-22.04,-19.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,-272.62,-86.16,-7.81,-44.811,-43.04,-320.55,-171.31,-23.759,51.52,-11.83,-6.28,3.73,-13.07,26.86,64.25,0.66,11.032,30.04,-6.19
1506,212.62,0.00,59.63,0.000,19.10,325.50,56.80,122.354,20.44,8.68,15.88,0.00,45.76,54.17,-21.69,0.00,13.278,34.54,-3.00
1507,-107.37,305.85,-16.59,-21.282,-52.34,-9.80,-155.33,-72.507,14.05,0.59,-24.07,24.18,-40.17,-69.50,-85.42,-6.22,-14.845,-26.55,-26.75
1508,-246.83,-157.77,-14.56,-66.344,-44.05,68.50,-88.08,9.557,64.90,-17.73,41.25,15.53,62.98,146.12,286.11,6.17,22.551,44.68,3.04
1509,0.83,40.27,14.93,18.625,0.00,-85.70,52.67,-9.458,19.22,2.08,-56.45,-60.98,-99.71,-148.13,-349.59,-12.00,-31.909,-127.95,33.80

In [70]:
y_1 = y.shift(-1).dropna().reset_index(drop=True)
y_1

0       1.0
1       0.0
2       0.0
3       1.0
4       0.0
       ...
1502    1.0
1503    0.0
1504    0.0
1505    1.0
1506    0.0
Name: Direction, Length: 1507, dtype: float64

In [71]:
X_1 = X_1.loc[3:,].reset_index(drop=True)
X_1

,NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,FTSE BURSA MAL TOP 100,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
0,-66.36,46.32,-20.12,2.231,7.17,-30.00,14.08,21.518,81.68,8.49,4.70,14.74,9.20,14.07,44.90,0.07,0.000,24.97,-7.72
1,0.00,55.68,16.23,51.864,-0.34,-7.75,-29.80,-30.658,-44.03,18.91,-12.20,27.72,-22.27,-35.02,-327.69,-1.90,-12.282,7.40,-12.32
2,-152.89,186.16,-5.63,-46.743,-3.66,52.55,7.22,-6.440,27.71,24.48,-2.76,37.70,0.66,19.31,64.17,-0.36,0.271,24.33,14.74
3,63.23,190.50,-23.77,10.780,30.05,92.05,-3.90,-8.687,34.15,-5.08,1.73,15.02,0.48,62.87,62.69,1.84,1.784,-22.04,-19.51
4,-229.97,-106.33,-16.88,-4.628,11.97,26.55,64.44,-8.487,29.50,-7.94,-21.24,1.88,-24.74,-125.13,-330.29,-3.49,-8.568,-52.13,19.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1502,-272.62,-86.16,-7.81,-44.811,-43.04,-320.55,-171.31,-23.759,51.52,-11.83,-6.28,3.73,-13.07,26.86,64.25,0.66,11.032,30.04,-6.19
1503,212.62,0.00,59.63,0.000,19.10,325.50,56.80,122.354,20.44,8.68,15.88,0.00,45.76,54.17,-21.69,0.00,13.278,34.54,-3.00
1504,-107.37,305.85,-16.59,-21.282,-52.34,-9.80,-155.33,-72.507,14.05,0.59,-24.07,24.18,-40.17,-69.50,-85.42,-6.22,-14.845,-26.55,-26.75
1505,-246.83,-157.77,-14.56,-66.344,-44.05,68.50,-88.08,9.557,64.90,-17.73,41.25,15.53,62.98,146.12,286.11,6.17,22.551,44.68,3.04
1506,0.83,40.27,14.93,18.625,0.00,-85.70,52.67,-9.458,19.22,2.08,-56.45,-60.98,-99.71,-148.13,-349.59,-12.00,-31.909,-127.95,33.80

In [72]:
df

,Date,Last Price,Volume,SMAVG (15),NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,...,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX,% Change,Direction
1,2017-01-04,2270.75,573172224.0,566080832.0,19594.16,22134.47,3368.31,5736.409,2045.64,8190.50,...,7189.74,4899.40,11584.31,19626.64,487.58,1530.926,8354.81,1176.69,0.572231,1
2,2017-01-05,2269.00,573475776.0,564809856.0,19520.69,22456.69,3367.79,5753.350,2041.95,8273.80,...,7195.31,4900.64,11584.94,19642.81,486.93,1522.103,8392.49,1180.31,-0.077067,0
3,2017-01-06,2276.98,485214848.0,549549952.0,19454.33,22503.01,3347.67,5755.581,2049.12,8243.80,...,7210.05,4909.84,11599.01,19687.71,487.00,1522.103,8417.46,1172.59,0.351697,1
4,2017-01-09,2268.90,532332864.0,541448000.0,19454.33,22558.69,3363.90,5807.445,2048.78,8236.05,...,7237.77,4887.57,11563.99,19360.02,485.10,1509.821,8424.86,1160.27,-0.354856,0
5,2017-01-10,2268.90,596464384.0,481377280.0,19301.44,22744.85,3358.27,5760.702,2045.12,8288.60,...,7275.47,4888.23,11583.30,19424.19,484.74,1510.092,8449.19,1175.01,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2022-12-23,3844.82,407580896.0,763465024.0,26235.25,19593.06,3828.22,7107.689,2313.69,17806.80,...,7473.01,6504.90,13940.93,23877.55,701.06,2054.329,10804.68,963.51,0.586806,1
1506,2022-12-27,3829.25,449987360.0,754168384.0,26447.87,19593.06,3887.85,7107.689,2332.79,18132.30,...,7473.01,6550.66,13995.10,23855.86,701.06,2067.607,10839.22,960.51,-0.404960,0
1507,2022-12-28,3783.22,438066304.0,740323072.0,26340.50,19898.91,3871.26,7086.407,2280.45,18122.50,...,7497.19,6510.49,13925.60,23770.44,694.84,2052.762,10812.67,933.76,-1.202063,0
1508,2022-12-29,3849.28,466689120.0,729421504.0,26093.67,19741.14,3856.70,7020.063,2236.40,18191.00,...,7512.72,6573.47,14071.72,24056.55,701.01,2075.313,10857.35,936.80,1.746132,1
1509,2022-12-30,3839.50,511646752.0,724693120.0,26094.50,19781.41,3871.63,7038.688,2236.40,18105.30,...,7451.74,6473.76,13923.59,23706.96,689.01,2043.404,10729.40,970.60,-0.254073,0

In [73]:
# splitting test train 
X_train, X_test, y_train, y_test = train_test_split(X_1, y_1, test_size= 0.3, random_state = 21, shuffle = False)
X_train.tail()

,NIKKEI 225,HANG SENG,SHANGHAI,SP ASX 200,KOSPI 100,NIFTY 50,TAIWAN INDEX,JAKARTA COMPOSITE,FTSE BURSA MAL TOP 100,STRAITS TIMES,EURO STOXX 50 PR,FTSE 100 INDEX,CAC 40 INDEX,DAX INDEX,FTSE MIB INDEX,AEX INDEX,OMX STOCKHOLM INDEX,SWISS MARKET INDEX,RTS INDEX
1049,8.62,134.29,32.61,-57.056,-18.00,76.40,58.58,65.032,109.24,-28.81,33.87,-4.74,65.58,102.31,109.46,2.93,9.617,51.80,-2.28
1050,175.08,478.09,124.61,-0.183,55.58,0.00,267.89,0.000,-33.71,26.29,25.72,11.36,43.21,29.14,195.41,5.68,31.196,-26.54,25.65
1051,506.19,-645.89,18.16,52.889,40.69,-143.85,75.62,93.530,-78.02,-10.79,-12.28,24.51,12.79,-67.00,-8.15,-6.30,3.302,-43.30,14.28
1052,49.14,94.04,-110.84,6.202,-8.68,-101.45,-5.85,-33.950,22.43,10.78,-3.52,-11.77,-10.58,-40.97,26.23,1.39,-7.134,27.40,24.49
1053,154.12,193.93,43.82,54.123,21.46,-19.05,63.83,-14.560,22.95,-0.49,21.12,53.91,19.46,96.16,121.67,4.85,18.313,77.15,8.82

In [74]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [75]:
X_test_scaled = scaler.transform(X_test)

In [76]:
model = SVC(kernel='rbf', C=1, gamma='scale',coef0=0.001, degree = 3)
model.fit(X_train_scaled,y_train)
pred = model.predict(X_test_scaled)

In [77]:
print ("Train Accuracy Score:",model.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",model.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 0.7770398481973435
Test Accuracy Score: 0.6865342163355408
Confusion Matrix: [[131  99]
 [ 43 180]]

In [78]:
log_reg = LogisticRegression(random_state=0, tol=1e-8, max_iter=5000, class_weight = 'balanced').fit(X_train_scaled, y_train)
pred = log_reg.predict(X_test_scaled)
print ("Train Accuracy Score:",log_reg.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",log_reg.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 0.7239089184060721
Test Accuracy Score: 0.6799116997792495
Confusion Matrix: [[150  80]
 [ 65 158]]

In [79]:
Rf = RandomForestClassifier(random_state=0)
Rf.fit(X_train_scaled, y_train)
pred = Rf.predict(X_test_scaled)
print ("Train Accuracy Score:",Rf.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",Rf.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 1.0
Test Accuracy Score: 0.6843267108167771
Confusion Matrix: [[137  93]
 [ 50 173]]

In [80]:
GB = GradientBoostingClassifier()
GB.fit(X_train_scaled, y_train)
pred = GB.predict(X_test_scaled)
print ("Train Accuracy Score:",GB.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",GB.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 0.8738140417457305
Test Accuracy Score: 0.6931567328918322
Confusion Matrix: [[144  86]
 [ 53 170]]

In [81]:
opt = BayesSearchCV(pipe, search_space, cv=3, n_iter=10, scoring='roc_auc', random_state = 8)
opt.fit(X_train_scaled, y_train)
print ("Train Accuracy Score:",opt.score(X_train_scaled, y_train))
print ("Test Accuracy Score:",opt.score(X_test_scaled, y_test))
print ("Confusion Matrix:", metrics.confusion_matrix(y_test, pred))

Train Accuracy Score: 0.7920232408194368
Test Accuracy Score: 0.7513062975238838
Confusion Matrix: [[144  86]
 [ 53 170]]